export const enum USER_TYPE {
	SUPER_ADMIN = 'SUPER_ADMIN',
	ADMIN = 'ADMIN',
	COMPANY_ADMIN = 'COMPANY_ADMIN',
	STORE_ADMIN = 'STORE_ADMIN',
	MANAGER = 'MANAGER',
}

export const USER_TYPE_ORDER = {
	SUPER_ADMIN: 1,
	ADMIN: 2,
	COMPANY_ADMIN: 3,
	STORE_ADMIN: 4,
	MANAGER: 5,
};
