export const enum USER_TYPE {
	SUPER_ADMIN = 'SUPER_ADMIN',
	ADMIN = 'ADMIN',
	COMPANY_ADMIN = 'COMPANY_ADMIN',
	STORE_ADMIN = 'STORE_ADMIN',
	MANAGER = 'MANAGER',
}

export const userTypeValues = {
	SUPER_ADMIN: USER_TYPE.SUPER_ADMIN,
	ADMIN: USER_TYPE.ADMIN,
	COMPANY_ADMIN: USER_TYPE.COMPANY_ADMIN,
	STORE_ADMIN: USER_TYPE.STORE_ADMIN,
	MANAGER: USER_TYPE.MANAGER,
};
