name: Dopecast_deployment

on:
  push:
    branches:
      - dopcast-management-apis

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install dependencies
        run: npm i

      - name: Build project
        run: npm run build:prod

      - name: Run tests
        run: npm run test

      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.DOPECAST_HOST }}
          username: ${{ secrets.DOPECAST_USERNAME }}
          port: ${{ secrets.DOPECAST_PORT }}
          key: ${{ secrets.DOPECAST_SSH_PRIVATE_KEY }}
          source: 'dist/*,package.json,.env.production,pm2.config.js'
          target: /home/monarch

      - name: Reload server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DOPECAST_HOST }}
          username: ${{ secrets.DOPECAST_USERNAME }}
          port: ${{ secrets.DOPECAST_PORT }}
          key: ${{ secrets.DOPECAST_SSH_PRIVATE_KEY }}
          script: |
            cd /home/monarch/
            npm install --production
            pm2 restart all
